### ISSUE TITLE
💡 IDEAS 💡

### ISSUE THREAD

**Issue by Gummibeer** [Astrotomic/opendor.me#1]
This issue is to keep track of all ideas. As soon as we decide to do an idea we will split it out into its own issue to track exact details and state.
New ideas should be posted as a comment and will be added to the list in this opening comment.

```md
* [ ] As a _..._ I want to ... - https://link-to-comment - #issue-number
```

We have 4 different user roles in our app:
* **Contributor/Developer** - _nearly all users_
* **Maintainer** - _users who own a repository or are a member of the organization owning_
* **Recruiter** - _users who are looking for developers_
* **Moderator/Administrator** - _users with special permissions to manage all content_

### Contributor

* [ ] As a _Contributor_ I want to add my availability for a job and type of contract. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-808915814 - #17
* [ ] As a _Contributor_ I want to add additional skill information (known programming languages). - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-808915814 - #18
* [ ] As a _Contributor_ I want to search for repositories in need of help. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-808915814
  * https://github.com/tighten/ozzie
* [ ] As a _Contributor_ I want to highlight some repositories - I did the most work for or whyever. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-808915814
* [ ] As a _Contributor_ I want to add my spoken languages. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-809178892
* [ ] As a _Contributor_ I want to link to more profiles - LinkedIn, Xing - so recruiters can contact me.
* [ ] As a _Contributor_ I want to search all my contributions with a single search field.
 
### Maintainer

* [ ] As a _Maintainer_ I want to highlight some repositories - the most downloaded, relevant, maintained. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-808915814
* [ ] As a _Maintainer_ I want to give special credits to outstanding contributors - achievements, medals, badges.
* [ ] As a _Maintainer_ I want to write a recommendation letter to heroic contributors.

### Organization

* [ ] As an _Organization_ I want to keep the member/admin roles from GitHub so not all members can manage organization details.
  * https://docs.github.com/en/rest/reference/orgs#list-organization-members

### Recruiter

* [ ] As a _Recruiter_ I want to search for developers by programming language.
* [ ] As a _Recruiter_ I want to search for developers by spoken languages. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-809178892
* [ ] As a _Recruiter_ I want to bookmark developers so I can find them later. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-809284551
* [x] ❌ As a _Recruiter_ I want to contact developers via platform for tracking. -https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-809284551
> @Gummibeer: Until further requests I will reject this one because of conflicts with recruiter tools, privacy and the primary target of opendor.me isn't a recruiting platform in it's original sense.
* [ ] As a _Recruiter_ I want to filter repositories on the contributor profile by language in the summary. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-809716254

### Any

* [ ] As _any user_ I want to report users, organizations, repositories to be reviewed as they don't follow the rules.
* [ ] As _any user_ I want to see all used languages in a repository.
  * https://docs.github.com/en/rest/reference/repos#list-repository-languages
* [ ] As _any user_ I want to see package platform links (npm, packagist ...) related to a repository.
* [x] ✅ As _any user_ I want to see the stars of a repository without clicking the GitHub link.
* [ ] As _any user_ I want to see which repository uses Treeware license-addition and how many trees it referenced.
```php
$response = (new Client())->request('get', 'https://api.ecologi.com/users/treeware/trees', [
    'query' => [
        'ref' => md5(Str::lower($package->owner . '/' . $package->package_name)),
    ],
]);
```
* [x] 🗒️ As _any user_ I want to see a maximum of 6 repositories per vendor on the profile page - additional will be collapsed. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-809274607 - #2 
* [ ] As _any user_ I want to get linked to a local contributors page per repository. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-811535014
* [x] ✅ As _any user_ I want to see that the profile could miss data as the system imports only repositories of registered users. - https://github.com/Astrotomic/opendor.me/issues/1#issuecomment-812926676

**Comment by SarahSibert** [comment]
Users:

- Highlight certain projects/repos
- Search for projects to contribute to by organisation/skill, any tags assigned by repo owner e.g. good first issue
- Search for recruiters (if they are signed up that way)
- Add additional skill info/background in a templates way
- Add availability - hours, type of contract

**Comment by SarahSibert** [comment]
Contributor:
- add spoken languages

Recruiter:
- search for Contributor by spoken languages

**Comment by Lloople** [comment]
As any user, I would like to see a max of 9 contributions per vendor. In case there are more than 9, show 8 plus a card with ( ... and 3 more contributions) which you can click to expand the information

**Comment by SarahSibert** [comment]
Recruiter:
- star/short-list/save Contributors
- contact Contributor via Platform (to record usage)

**Comment by SarahSibert** [comment]
Recruiter
- on a Contributor’s page, add the ability to filter repos by language in the summary

**Comment by mallardduck** [comment]
Contributor

- on the home page I would like to see the "Contributors" link on the featured repositories to link to a "local" page instead of GitHub. The local page could better feature the Members/Users that signed up to the App rather than all of the contributors on the GitHub page.

**Comment by Gummibeer** [comment]
Feedback by @jessarcher:

* As a newly registered user I want to see that it can take some minutes until all my data is imported.
* As anyone want to see that the users profile could Miss data as the system imports only repositories of registered users.
* As anyone I would like to get better search results in homepage user search.

**Comment by SarahSibert** [comment]
User:
- choose which 6 repositories are shown and/or be able to order by newest/most starred etc.

**Comment by zaherg** [comment]
User:

- ability to choose the correct gender reference, for example not everyone use the term "they", in sentence like "they are also a member of", for me it should be "he is also a member of"

**Comment by SarahSibert** [comment]
Recruiter:
- browse the contributors and repositories not just search

**Comment by Gummibeer** [comment]
Please use discussions for further Ideas.
https://github.com/Astrotomic/opendor.me/discussions/new?category=ideas
